### PR TITLE
Add MTG Card Fetcher using Scryfall

### PR DESCRIPTION
**Pull request by ZeldaZach**
New module to allow users to `!card card name` to get the details of Magic: the Gathering cards

### CODE REVIEW

**Comment by BrandenB** [comment]
I'm curious, did you test this? Last time I checked, Rhino (our JavaScript engine) did not support the keyword `const`.

**Comment by ZeldaZach** [comment]
Yep, tested on two different instances of the bot (one mac, one linux) and it works as expected.

If it doesn't support legacy systems, I can translate back to `var` components. It's small enough of a file that I don't _think_ it matters whether i use const or not.

**Comment by BrandenB** [comment]
It will work on all system, since it's the same library shipped to everyone, I am just extremely surprised that it works, since last time we check Rhino only supported ES5, which I do not believe `const` to be apart of. I do know that `let` does not work on Rhino, never tried `const` though.

Anyway, everything looks good, if you tested, merging it.

**Comment by ZeldaZach** [comment]
Sounds good! Thanks for the quick review process

**Pull request merged**
